#!/bin/bash

init_docker() {
  docker run -it --rm -v $(pwd):/app -p 3000:3000 -p 5858:5858 jaiminho "$@"
}

case "$1" in
  "build" )
    docker build -t jaiminho . ;;

  "install" )
    init_docker npm i ;;

  "test" )
    init_docker npm test ;;

  "start" )
    init_docker npm start ;;

  "debug" )
    init_docker npm run nodemon ;;

  "run" )
    init_docker ${@:2} ;;

  "help" | * )
    cat<<EOF
    Jaiminho CLI
    Usage: ./jaiminho <command> [<anothercommand>]

    Available commands:
    build:                Build docker image
    install:              Install NodeJS packages
    test:                 Run tests
    start:                Start server
    debug:                Start server with debugger (on port 5858)
    run <anothercommand>: Run docker image with command inside container passed to <anothercommand>

EOF
;;
esac
